// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCTYVOmc8HI5liZ6RGmsBCPn9R-GvDqsA',
    appId: '1:326124524834:web:b0e19cf9af0b42da60817b',
    messagingSenderId: '326124524834',
    projectId: 'r56jc3cyhr225qmjt3mllc0vtjxesd',
    authDomain: 'r56jc3cyhr225qmjt3mllc0vtjxesd.firebaseapp.com',
    storageBucket: 'r56jc3cyhr225qmjt3mllc0vtjxesd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVhVOplrppLX5_4XabkF1WgDXeFw6ne1Y',
    appId: '1:326124524834:android:ac5d0977013a588260817b',
    messagingSenderId: '326124524834',
    projectId: 'r56jc3cyhr225qmjt3mllc0vtjxesd',
    storageBucket: 'r56jc3cyhr225qmjt3mllc0vtjxesd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEI83PRRqdSl7o35cIdyzidc0jN7HHc_A',
    appId: '1:326124524834:ios:d2c168797babc98a60817b',
    messagingSenderId: '326124524834',
    projectId: 'r56jc3cyhr225qmjt3mllc0vtjxesd',
    storageBucket: 'r56jc3cyhr225qmjt3mllc0vtjxesd.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
